// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_champion = "CgkIy9Do4aEQEAIQCA"; // <GPGSID>
        public const string achievement_strategist = "CgkIy9Do4aEQEAIQBw"; // <GPGSID>
        public const string achievement_kill_25_enemies = "CgkIy9Do4aEQEAIQAg"; // <GPGSID>
        public const string achievement_destroy_5_space_derbies = "CgkIy9Do4aEQEAIQAw"; // <GPGSID>
        public const string achievement_kill_5_enemies = "CgkIy9Do4aEQEAIQAQ"; // <GPGSID>
        public const string achievement_rookie = "CgkIy9Do4aEQEAIQBg"; // <GPGSID>
        public const string leaderboard_highscore_leaderboard = "CgkIy9Do4aEQEAIQCw"; // <GPGSID>
        public const string achievement_legend = "CgkIy9Do4aEQEAIQCQ"; // <GPGSID>
        public const string achievement_destroy_25_space_debris = "CgkIy9Do4aEQEAIQBA"; // <GPGSID>
        public const string achievement_ascended_toward_radiant_astral_realms = "CgkIy9Do4aEQEAIQCg"; // <GPGSID>
        public const string achievement_open_instructions = "CgkIy9Do4aEQEAIQBQ"; // <GPGSID>

}

